audio: Resolve symbol name conflicts
Well, this is because we are building everything inline.

ld.lld: error: duplicate symbol: ftm_mode
>>> defined at pcie_bus.c:21 (../drivers/net/wireless/ath/wil6210/pcie_bus.c:21)
>>>            drivers/net/wireless/ath/wil6210/pcie_bus.o:(ftm_mode) in archive built-in.a
>>> defined at tfa98xx_v6.c:463 (../techpack/audio/../../oplus/kernel_4.19/audio/codecs/tfa98xx-v6/tfa98xx_v6.c:463)
>>>            oplus/kernel_4.19/audio/codecs/tfa98xx-v6/tfa98xx_v6.o:(.bss+0x8) in archive built-in.a

Signed-off-by: LibXZR <i@xzr.moe>